version: '3.3'

services:
  portainer-ce:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=docker.$DOMAIN_NAME
      - LETSENCRYPT_HOST=docker.$DOMAIN_NAME
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    labels:
      caddy: docker.$DOMAIN_NAME
      caddy.reverse_proxy: "{{upstreams 9000}}"
    networks:
      - caddy
    ports:
      - '9443:9443'

  netdata:
    image: firehol/netdata
    container_name: netdata
    hostname: monitor.$DOMAIN_NAME
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      caddy: monitor.$DOMAIN_NAME
      caddy.reverse_proxy: "{{upstreams 19999}}"
    networks:
      - caddy

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8.3-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    labels:
      caddy: $DOMAIN_NAME, www.$DOMAIN_NAME
      caddy.respond: '"Hello World" 200'
    networks:
      - caddy

  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'

  filebeat:
    image: bargenson/filebeat
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    environment:
    - LOGSTASH_HOST=$DOMAIN_NAME
    - LOGSTASH_PORT=5044
    - SHIPPER_NAME=aWonderfulName

  my-filebeat:
    container_name: my-filebeat
    image: 'docker.elastic.co/beats/filebeat:7.4.2'
    volumes:
      - './docker-elk/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    user: root


volumes:
  portainer_data:
  caddy_data: {}


networks:
  caddy:
    external: true
