version: '3.3'

services:
  portainer-ce:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=docker.$DOMAIN_NAME
      - LETSENCRYPT_HOST=docker.$DOMAIN_NAME
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    ports:
      - '8000:8000'
      - '9443:9443'

  netdata:
    image: firehol/netdata
    container_name: netdata
    hostname: monitor.$DOMAIN_NAME
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - url=https://monitor.yoman.online
    networks:
      - internal

  caddy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
    networks:
      - web
      - internal


volumes:
  portainer_data:


networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
