version: '3.3'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "default"
      - "proxy-tier"

  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "proxy"
    depends_on:
      - "proxy"
    networks:
      - "default"
      - "proxy-tier"

  portainer-ce:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=docker.$DOMAIN_NAME
      - LETSENCRYPT_HOST=docker.$DOMAIN_NAME
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    ports:
      - '8000:8000'
      - '9443:9443'

  hello-world:
    image: hello-world

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=gitea.$DOMAIN_NAME
      - LETSENCRYPT_HOST=gitea.$DOMAIN_NAME
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - VIRTUAL_PORT=3000
      - ROOT_URL=https://gitea.$DOMAIN_NAME
      - DOMAIN=gitea.$DOMAIN_NAME
      - PROTOCOL=http
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
    ports:
      - "5000:3000"
      - "222:22"
    networks:
      - proxy-tier
      - default


volumes:
  certs:
  vhost.d:
  html:
  portainer_data:


networks:
  proxy-tier:
