# filebeat.inputs:
#   - type: log
#     paths:
#       - '/var/lib/docker/containers/*/*.log'
#     json.message_key: log
#     json.keys_under_root: true
#     processors:
#       - add_docker_metadata: ~

# output.elasticsearch:
#   hosts: ["docker-elk-elasticsearch-1:9200"]
#   username: '${ELASTICSEARCH_USERNAME:elastic}'
#   password: '${ELASTICSEARCH_PASSWORD:changeme}'



filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml # enable all modules (nginx, kafka, redis, etc)
    reload.enabled: false

filebeat.autodiscover: # auto-discover tagged docker container
  providers:
    - type: docker
      node: ${NODE_NAME}
      hints: 
        enabled: true
        default_config: 
          enabled: false
          type: container
          paths:
            - /var/lib/docker/containers/${data.container.id}/*.log

setup:
  kibana.host: '${KIBANA_URL:http://docker-elk-kibana-1:5601}'
  dashboards.enable: true

processors:
  - add_docker_metadata: ~ # add docker metadata (container id, name, image and labels)
  # - decode_json_fields:
  #     fields: ["message"]
  #     add_error_key: true
  #     expand_keys: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_URL:http://docker-elk-elasticsearch-1:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_PASSWORD:NigEVfhBpEbw4Kt}'