server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: '${LOKI_URL}'
    basic_auth:
      username: '${LOKI_USERNAME}'
      password: '${LOKI_PASSWORD}'

scrape_configs:
  - job_name: swarm-services
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Drop Promtail's own logs
      - source_labels: ['__meta_docker_container_name']
        regex: 'promtail' # Or the exact name of your promtail container if it's different
        action: drop
      # Include only services with co.elastic.logs/enabled: 'true'
      - source_labels: ['__meta_docker_container_label_co_elastic_logs_enabled']
        regex: 'true'
        action: keep
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_stack_name']
        target_label: 'stack'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'